apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGODB_USERNAME: mongo
  MONGODB_CLUSTER_URL: mongocluster.yo3gpdn.mongodb.net
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"